import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#004d62",
        "surface-bright": "#f8f9ff",
        "on-primary-fixed": "#001b3d",
        "on-error": "#ffffff",
        "surface-container": "#e5eeff",
        "surface-container-low": "#eff4ff",
        error: "#ba1a1a",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#e0e3e5",
        "on-primary-fixed-variant": "#2e476f",
        background: "#f8f9ff",
        "inverse-primary": "#aec7f6",
        "primary-fixed-dim": "#aec7f6",
        "on-secondary-fixed": "#001f29",
        "primary-container": "#002046",
        "outline-variant": "#c4c6cf",
        "on-surface-variant": "#44474e",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-container": "#09657f",
        "tertiary-container": "#1e2123",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#85888a",
        "surface-variant": "#d3e4fe",
        "on-surface": "#0b1c30",
        "on-tertiary-fixed": "#191c1e",
        "secondary-container": "#9ae1ff",
        "secondary-fixed": "#baeaff",
        tertiary: "#070a0b",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-tertiary-fixed-variant": "#444749",
        "surface-tint": "#465f88",
        primary: "#00091b",
        outline: "#74777f",
        "inverse-surface": "#213145",
        "primary-fixed": "#d6e3ff",
        "secondary-fixed-dim": "#89d0ed",
        "surface-dim": "#cbdbf5",
        "on-primary-container": "#7089b4",
        "on-background": "#0b1c30",
        "surface-container-high": "#dce9ff",
        surface: "#f8f9ff",
        "surface-container-highest": "#d3e4fe",
        secondary: "#0c6780",
        "inverse-on-surface": "#eaf1ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "section-gap": "72px",
        "margin-mobile": "16px",
        unit: "8px",
        gutter: "24px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        "headline-lg": ["var(--font-geist-sans)", "system-ui", "sans-serif"],
        "headline-md": ["var(--font-geist-sans)", "system-ui", "sans-serif"],
        "body-lg": ["var(--font-geist-sans)", "system-ui", "sans-serif"],
        "display-lg": ["var(--font-geist-sans)", "system-ui", "sans-serif"],
        "display-lg-mobile": ["var(--font-geist-sans)", "system-ui", "sans-serif"],
        "body-md": ["var(--font-geist-sans)", "system-ui", "sans-serif"],
        "label-md": ["var(--font-geist-sans)", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["21px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["17px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": [
          "54px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "display-lg-mobile": [
          "34px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "body-md": ["15px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" },
        ],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};

export default config;
